local _, ns = ...

--- Built-in glow texture options for the overshield glow selector.
-- Each entry is { asset, displayName }. The asset may be a texture path or an atlas
-- name; OptionsDropdowns decides which icon prefix to render it with.
-- LSM-registered spark/pip textures are merged in on top of these at build time.
ns.GlowTextureCatalog = {
	{ "Interface\\RaidFrame\\Shield-Overshield", "Default Glow" },
	{ "Interface\\CastingBar\\UI-CastingBar-Spark", "Cast Bar Spark" },
	{ "Interface\\Cooldown\\star4", "Star4" },
	{ "Interface\\Cooldown\\starburst", "Starburst" },
	{ "Warlock-Shard-Spark", "Warlock Spark" },
	{ "cosmic-bar-spark", "Cosmic Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Kyrian", "Kyrian Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Glow-Kyrian", "Kyrian Glow Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Necrolord", "Necrolord Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Glow-Necrolord", "Necrolord Glow Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Nightfae", "Night Fae Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Glow-Nightfae", "Night Fae Glow Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Venthyr", "Venthyr Spark" },
	{ "CovenantSanctum-Reservoir-Spark-Glow-Venthyr", "Venthyr Glow Spark" },
	{ "UI-Frame-DastardlyDuos-ProgressBar-Spark", "Dastardly Duos Spark" },
	{ "Garr_MissionFX-Glow", "Mission Glow" },
	{ "Garr_MissionFX-Lines", "Mission Lines" },
	{ "GenericWidgetBar-Spark-Line", "Widget Spark Line" },
	{ "gradientbar-marker-diamond", "Diamond Marker" },
	{ "gradientbar-marker-plain", "Plain Marker" },
	{ "gradientbar-Spark-arrows", "Spark Arrows" },
	{ "islands-queue-progressbar-spark", "Islands Queue Spark" },
	{ "Legionfall_BarSpark", "Legionfall Spark" },
	{ "Mage-ArcaneCharge-Spark", "Arcane Charge Spark" },
	{ "Mage-ArcaneCharge-SmallSpark", "Small Arcane Spark" },
	{ "objectivewidget-bar-spark-left", "Objective Left Spark" },
	{ "objectivewidget-bar-spark-neutral", "Objective Neutral Spark" },
	{ "objectivewidget-bar-spark-right", "Objective Right Spark" },
	{ "Insanity-Spark", "Insanity Spark" },
	{ "honorsystem-bar-spark", "Honor Bar Spark" },
	{ "UI-World-Quest-spark", "World Quest Spark" },
	{ "stormcapture-spark-air", "Air Capture Spark" },
	{ "stormcapture-spark-earth", "Earth Capture Spark" },
	{ "stormcapture-spark-water", "Water Capture Spark" },
	{ "ui-castingbar-pip-red", "Red Pip" },
	{ "cast-empowered-pipflare", "Empowered Pip Flare" },
	{ "UI-Frame-Bar-Spark", "Frame Bar Spark" },
	{ "plunderstorm-stormbar-spark", "Plunderstorm Spark" },
	{ "BastionAnima-Horizontal-Spark", "Bastion Anima Spark" },
	{ "widgetstatusbar-spark", "Status Bar Spark" },
	{ "machinebar-spark", "Machine Bar Spark" },
	{ "worldstate-capturebar-spark-boss", "Boss Capture Spark" },
	{ "worldstate-capturebar-spark-factions", "Faction Capture Spark" },
	{ "worldstate-capturebar-spark-lfd", "LFD Capture Spark" },
	{ "worldstate-capturebar-spark-target", "Target Capture Spark" },
	{ "worldstate-capturebar-spark-white", "White Capture Spark" },
	{ "worldstate-capturebar-spark-bastionarmor", "Bastion Armor Spark" },
	{ "worldstate-capturebar-spark-neutral-bastionarmor", "Neutral Bastion Spark" },
	{ "worldstate-capturebar-spark-casualformal-embercourt", "Ember Court Spark" },
	{ "XPBarAnim-OrangeSpark", "Orange XP Spark" },
}
